toDo:
  botones
  nombres de carpetas
  resolver filtro proyectos
    agregar fondo
  seleccionar colores

home:
  - fix mapa
  - botones
  - qa diseño
  - primary violeta, footer amarillo

proyectos:
  - filtros paises y sdgs
  - + svg

proyecto:
  - add file to download
  - el otro boton?

nominate: check
partner:


capacity building:
  - arreglar columnas
  - pasar a html?

about eidos: lorem
about y20:

logos: content





We have offices in:
Buenos Aires, Argentina
Bristol, United Kingdom
Email: siw@eidosglobal.org
Website: aeidos.com.ar
