title: Proyecto
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea

  location:
    label: Location
    type:  text

  quote:
    label: Quote
    type:  text

  photo:
    label: Foto
    type:  image
    required: true

  tags:
    label: Tags
    type: tags
    lower: true

  text2:
    label: Texto largo
    type:  textarea
