title: Proyecto
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  location:
    label: Location
    type:  text
  tags:
    label: Tags
    type: tags
    lower: true
